<a href="https://colab.research.google.com/github/YannPhamVan/stock-markets-analytics-zoomcamp/blob/main/cohorts/2025/01-intro-and-data-sources-homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Module 1 Homework (2025 cohort)

In this homework, we're going to download finance data from various sources and make simple calculations or analysis.

---
### Question 1: [Index] S&P 500 Stocks Added to the Index

**Which year had the highest number of additions?**

Using the list of S&P 500 companies from Wikipedia's [S&P 500 companies page](https://en.wikipedia.org/wiki/List_of_S%26P_500_companies), download the data including the year each company was added to the index.

Hint: you can use [pandas.read_html](https://pandas.pydata.org/docs/reference/api/pandas.read_html.html) to scrape the data into a DataFrame.

Steps:
1. Create a DataFrame with company tickers, names, and the year they were added.
2. Extract the year from the addition date and calculate the number of stocks added each year.
3. Which year had the highest number of additions (1957 doesn't count, as it was the year when the S&P 500 index was founded)? Write down this year as your answer (the most recent one, if you have several records).

*Context*:
> "Following the announcement, all four new entrants saw their stock prices rise in extended trading on Friday" - recent examples of S&P 500 additions include DASH, WSM, EXE, TKO in 2025 ([Nasdaq article](https://www.nasdaq.com/articles/sp-500-reshuffle-dash-tko-expe-wsm-join-worth-buying)).

*Additional*: How many current S&P 500 stocks have been in the index for more than 20 years? When stocks are added to the S&P 500, they usually experience a price bump as investors and index funds buy shares following the announcement.

In [64]:
# IMPORTS
import numpy as np
import pandas as pd
from datetime import date, timedelta
import yfinance as yf

In [2]:
df = pd.read_html("https://en.wikipedia.org/wiki/List_of_S%26P_500_companies")[0][["Symbol", "Security", "Date added"]]
df

    Symbol             Security  Date added
0      MMM                   3M  1957-03-04
1      AOS          A. O. Smith  2017-07-26
2      ABT  Abbott Laboratories  1957-03-04
3     ABBV               AbbVie  2012-12-31
4      ACN            Accenture  2011-07-06
..     ...                  ...         ...
498    XYL           Xylem Inc.  2011-11-01
499    YUM          Yum! Brands  1997-10-06
500   ZBRA   Zebra Technologies  2019-12-23
501    ZBH        Zimmer Biomet  2001-08-07
502    ZTS               Zoetis  2013-06-21

[503 rows x 3 columns]

In [3]:
df["Date added"] = pd.to_datetime(df["Date added"])
df["Year"] = df["Date added"].dt.year
df

    Symbol             Security Date added  Year
0      MMM                   3M 1957-03-04  1957
1      AOS          A. O. Smith 2017-07-26  2017
2      ABT  Abbott Laboratories 1957-03-04  1957
3     ABBV               AbbVie 2012-12-31  2012
4      ACN            Accenture 2011-07-06  2011
..     ...                  ...        ...   ...
498    XYL           Xylem Inc. 2011-11-01  2011
499    YUM          Yum! Brands 1997-10-06  1997
500   ZBRA   Zebra Technologies 2019-12-23  2019
501    ZBH        Zimmer Biomet 2001-08-07  2001
502    ZTS               Zoetis 2013-06-21  2013

[503 rows x 4 columns]

In [4]:
df.groupby("Year").count().sort_values(by="Symbol", ascending=False)

      Symbol  Security  Date added
Year
1957      53        53          53
2016      23        23          23
2017      23        23          23
2019      22        22          22
2008      17        17          17
2024      16        16          16
2022      16        16          16
2023      15        15          15
2021      15        15          15
2015      14        14          14
2018      14        14          14
1997      14        14          14
2012      14        14          14
2002      13        13          13
2007      12        12          12
2020      12        12          12
2009      12        12          12
1976      11        11          11
1998      11        11          11
2006      10        10          10
2013      10        10          10
2011      10        10          10
2000       9         9           9
2010       9         9           9
1999       9         9           9
2014       8         8           8
2001       8         8           8
1995       7         7           7
1994       7         7           7
1985       7         7           7
2005       7         7           7
2004       6         6           6
1982       5         5           5
1984       5         5           5
2003       5         5           5
2025       5         5           5
1989       5         5           5
1988       4         4           4
1980       3         3           3
1981       3         3           3
1993       3         3           3
1986       3         3           3
1983       3         3           3
1992       3         3           3
1972       2         2           2
1965       2         2           2
1969       2         2           2
1970       2         2           2
1987       2         2           2
1975       2         2           2
1973       2         2           2
1979       2         2           2
1996       2         2           2
1991       1         1           1
1978       1         1           1
1964       1         1           1
1974       1         1           1

In [5]:
df.loc[(date.today().year - df['Year']) > 20].count()

Symbol        219
Security      219
Date added    219
Year          219
dtype: int64


---
### Question 2. [Macro] Indexes YTD (as of 1 May 2025)

**How many indexes (out of 10) have better year-to-date returns than the US (S&P 500) as of May 1, 2025?**

Using Yahoo Finance World Indices data, compare the year-to-date (YTD) performance (1 January-1 May 2025) of major stock market indexes for the following countries:
* United States - S&P 500 (^GSPC)
* China - Shanghai Composite (000001.SS)
* Hong Kong - HANG SENG INDEX (^HSI)
* Australia - S&P/ASX 200 (^AXJO)
* India - Nifty 50 (^NSEI)
* Canada - S&P/TSX Composite (^GSPTSE)
* Germany - DAX (^GDAXI)
* United Kingdom - FTSE 100 (^FTSE)
* Japan - Nikkei 225 (^N225)
* Mexico - IPC Mexico (^MXX)
* Brazil - Ibovespa (^BVSP)

*Hint*: use start_date='2025-01-01' and end_date='2025-05-01' when downloading daily data in yfinance

Context:
> [Global Valuations: Who's Cheap, Who's Not?](https://simplywall.st/article/beyond-the-us-global-markets-after-yet-another-tariff-update) article suggests "Other regions may be growing faster than the US and you need to diversify."

Reference: Yahoo Finance World Indices - https://finance.yahoo.com/world-indices/

In [13]:
start_date = '2024-12-30'
end_date = '2025-05-02'
tickers = ["^GSPC", "000001.SS", "^HSI", "^AXJO", "^NSEI", "^GSPTSE", "^GDAXI", "^FTSE", "^N225", "^MXX", "^BVSP"]

In [37]:
data = yf.download(tickers, start=start_date, end=end_date)["Close"]
index_values = data.T
index_values.fillna(method="ffill", limit=2, axis=1, inplace=True)
index_values

[*********************100%***********************]  11 of 11 completed
<ipython-input-37-76df8f708142>:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  index_values.fillna(method="ffill", limit=2, axis=1, inplace=True)

Date,2024-12-30,2024-12-31,2025-01-01,2025-01-02,2025-01-03,2025-01-06,2025-01-07,2025-01-08,2025-01-09,2025-01-10,...,2025-04-18,2025-04-21,2025-04-22,2025-04-23,2025-04-24,2025-04-25,2025-04-28,2025-04-29,2025-04-30,2025-05-01
Ticker,,,,,,,,,,,,,,,,,,,,,
000001.SS,3407.325928,3351.762939,3351.762939,3262.561035,3211.429932,3206.923096,3229.644043,3230.167969,3211.393066,3168.523926,...,3276.729980,3291.434082,3299.757080,3296.354980,3297.288086,3295.060059,3288.415039,3286.655029,3279.031006,3279.031006
^AXJO,8235.000000,8159.100098,8159.100098,8201.200195,8250.500000,8288.500000,8285.099609,8349.099609,8329.200195,8294.099609,...,7819.100098,7819.100098,7816.700195,7920.500000,7968.200195,7968.200195,7997.100098,8070.600098,8126.200195,8145.600098
^BVSP,120283.000000,120283.000000,120283.000000,120125.000000,118533.000000,120022.000000,121163.000000,119625.000000,119781.000000,118856.000000,...,129650.000000,129650.000000,130464.000000,132216.000000,134580.000000,134739.000000,135016.000000,135093.000000,135067.000000,135067.000000
^FTSE,8121.000000,8173.000000,8173.000000,8260.099609,8224.000000,8249.700195,8245.299805,8251.000000,8319.700195,8248.500000,...,8275.700195,8275.700195,8328.599609,8403.200195,8407.400391,8415.299805,8417.299805,8463.500000,8494.900391,8496.799805
^GDAXI,19909.140625,19909.140625,19909.140625,20024.660156,19906.080078,20216.189453,20340.570312,20329.939453,20317.099609,20214.789062,...,21205.859375,21205.859375,21293.529297,21961.970703,22064.509766,22242.449219,22271.669922,22425.830078,22496.980469,22496.980469
^GSPC,5906.939941,5881.629883,5881.629883,5868.549805,5942.470215,5975.379883,5909.029785,5918.250000,5918.250000,5827.040039,...,5282.700195,5158.200195,5287.759766,5375.859863,5484.770020,5525.209961,5528.750000,5560.830078,5569.060059,5604.140137
^GSPTSE,24620.599609,24727.900391,24727.900391,24898.000000,25073.500000,24999.800781,24929.900391,25051.699219,25073.400391,24767.699219,...,24192.800781,24008.900391,24306.000000,24472.699219,24727.500000,24710.500000,24798.599609,24874.500000,24841.699219,24795.599609
^HSI,20041.419922,20059.949219,20059.949219,19623.320312,19760.269531,19688.289062,19447.580078,19279.839844,19240.890625,19064.289062,...,21395.140625,21395.140625,21562.320312,22072.619141,21909.759766,21980.740234,21971.960938,22008.109375,22119.410156,22119.410156
^MXX,48837.718750,49513.269531,49513.269531,49765.199219,48957.238281,49493.558594,50085.500000,49634.261719,49807.960938,49596.699219,...,53018.570312,53758.750000,54777.839844,55766.578125,56382.000000,56720.121094,56980.128906,55613.429688,56259.281250,56259.281250
^N225,39894.539062,39894.539062,39894.539062,NaN,NaN,39307.050781,40083.300781,39981.058594,39605.089844,39190.398438,...,34730.281250,34279.921875,34220.601562,34868.628906,35039.148438,35705.738281,35839.988281,35839.988281,36045.378906,36452.300781
^NSEI,23644.900391,23644.800781,23742.900391,24188.650391,24004.750000,23616.050781,23707.900391,23688.949219,23526.500000,23431.500000,...,23851.650391,24125.550781,24167.250000,24328.949219,24246.699219,24039.349609,24328.500000,24335.949219,24334.199219,24334.199219

In [38]:
index_values["ytd_2025-05-01"] = index_values["2025-05-01"] / index_values["2025-01-01"] - 1

In [50]:
snp500_ytd_2025_05_01 = index_values.loc["^GSPC"]["ytd_2025-05-01"]

In [42]:
index_values["ytd_2025-05-01"].sort_values(ascending=False)

Ticker
^MXX         0.136247
^GDAXI       0.129982
^BVSP        0.122910
^HSI         0.102665
^FTSE        0.039618
^NSEI        0.024904
^GSPTSE      0.002738
^AXJO       -0.001655
000001.SS   -0.021700
^GSPC       -0.047179
^N225       -0.086283
Name: ytd_2025-05-01, dtype: float64

In [52]:
index_values.loc[index_values["ytd_2025-05-01"] > snp500_ytd_2025_05_01]["ytd_2025-05-01"].count()

np.int64(9)

*Additional*: How many of these indexes have better returns than the S&P 500 over 3, 5, and 10 year periods? Do you see the same trend?
Note: For simplicity, ignore currency conversion effects.)

In [66]:
def sort_returns(tickers: list, years_before: int) -> pd.DataFrame:
    end_date = date.today()
    # Calculate start date using timedelta
    start_date = end_date - timedelta(days=years_before*365 + 5) # Add a few extra days to ensure we get data on or after the exact start date
    data = yf.download(tickers, start=start_date, end=end_date)["Close"]
    index_values = data.T
    index_values.fillna(method="ffill", limit=4, axis=1, inplace=True)

    # Access the last available date for the end price
    end_price_date = index_values.columns[-1]
    # Access the first available date for the start price
    start_price_date = index_values.columns[0]

    index_values[f"return_{years_before}_years"] = index_values[end_price_date] / index_values[start_price_date] - 1
    return index_values[f"return_{years_before}_years"].sort_values(ascending=False)

In [67]:
sort_returns(tickers, 3)

[*********************100%***********************]  11 of 11 completed
<ipython-input-66-34e248080bf6>:7: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  index_values.fillna(method="ffill", limit=4, axis=1, inplace=True)

Ticker
^GDAXI       0.690011
^NSEI        0.527906
^GSPC        0.487384
^N225        0.389746
^GSPTSE      0.281340
^BVSP        0.270408
^FTSE        0.179702
^AXJO        0.170077
^HSI         0.139209
^MXX         0.133779
000001.SS    0.064134
Name: return_3_years, dtype: float64

In [68]:
sort_returns(tickers, 5)

[*********************100%***********************]  11 of 11 completed
<ipython-input-66-34e248080bf6>:7: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  index_values.fillna(method="ffill", limit=4, axis=1, inplace=True)

Ticker
^NSEI        1.741192
^GDAXI       1.105327
^GSPC        0.952753
^N225        0.804331
^GSPTSE      0.725609
^BVSP        0.694856
^MXX         0.621295
^AXJO        0.500251
^FTSE        0.436907
000001.SS    0.161122
^HSI        -0.032733
Name: return_5_years, dtype: float64

In [69]:
sort_returns(tickers, 10)

[*********************100%***********************]  11 of 11 completed
<ipython-input-66-34e248080bf6>:7: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  index_values.fillna(method="ffill", limit=4, axis=1, inplace=True)

Ticker
^NSEI        1.938089
^GSPC        1.729377
^BVSP        1.534601
^GDAXI       0.999963
^N225        0.833780
^GSPTSE      0.702542
^AXJO        0.475965
^MXX         0.301652
^FTSE        0.239814
^HSI        -0.156882
000001.SS   -0.281094
Name: return_10_years, dtype: float64


---
### Question 3. [Index] S&P 500 Market Corrections Analysis


**Calculate the median duration (in days) of significant market corrections in the S&P 500 index.**

For this task, define a correction as an event when a stock index goes down by **more than 5%** from the closest all-time high maximum.

Steps:
1. Download S&P 500 historical data (1950-present) using yfinance
2. Identify all-time high points (where price exceeds all previous prices)
3. For each pair of consecutive all-time highs, find the minimum price in between
4. Calculate drawdown percentages: (high - low) / high Ã— 100
5. Filter for corrections with at least 5% drawdown
6. Calculate the duration in days for each correction period
7. Determine the 25th, 50th (median), and 75th percentiles for correction durations

*Context:*
> * Investors often wonder about the typical length of market corrections when deciding "when to buy the dip" ([Reddit discussion](https://www.reddit.com/r/investing/comments/1jrqnte/when_are_you_buying_the_dip/?rdt=64135)).

> * [A Wealth of Common Sense - How Often Should You Expect a Stock Market Correction?](https://awealthofcommonsense.com/2022/01/how-often-should-you-expect-a-stock-market-correction/)

*Hint (use this data to compare with your results)*: Here is the list of top 10 largest corrections by drawdown:
* 2007-10-09 to 2009-03-09: 56.8% drawdown over 517 days
* 2000-03-24 to 2002-10-09: 49.1% drawdown over 929 days
* 1973-01-11 to 1974-10-03: 48.2% drawdown over 630 days
* 1968-11-29 to 1970-05-26: 36.1% drawdown over 543 days
* 2020-02-19 to 2020-03-23: 33.9% drawdown over 33 days
* 1987-08-25 to 1987-12-04: 33.5% drawdown over 101 days
* 1961-12-12 to 1962-06-26: 28.0% drawdown over 196 days
* 1980-11-28 to 1982-08-12: 27.1% drawdown over 622 days
* 2022-01-03 to 2022-10-12: 25.4% drawdown over 282 days
* 1966-02-09 to 1966-10-07: 22.2% drawdown over 240 days

---
### Question 4.  [Stocks] Earnings Surprise Analysis for Amazon (AMZN)


**Calculate the median 2-day percentage change in stock prices following positive earnings surprises days.**

Steps:
1. Load earnings data from CSV ([ha1_Amazon.csv](ha1_Amazon.csv)) containing earnings dates, EPS estimates, and actual EPS
2. Download complete historical price data using yfinance
3. Calculate 2-day percentage changes for all historical dates: for each sequence of 3 consecutive trading days (Day 1, Day 2, Day 3), compute the return as Close_Day3 / Close_Day1 - 1. (Assume Day 2 may correspond to the earnings announcement.)
4. Identify positive earnings surprises (where "actual EPS > estimated EPS" OR "Surprise (%)>0")
5. Calculate 2-day percentage changes following positive earnings surprises
6. Compare the median 2-day percentage change for positive surprises vs. all historical dates

Context: Earnings announcements, especially when they exceed analyst expectations, can significantly impact stock prices in the short term.

Reference: Yahoo Finance earnings calendar - https://finance.yahoo.com/calendar/earnings?symbol=AMZN

*Additional*: Is there a correlation between the magnitude of the earnings surprise and the stock price reaction? Does the market react differently to earnings surprises during bull vs. bear markets?)

---
### Question 5.  [Exploratory, optional] Brainstorm potential idea for your capstone project

**Free text answer**

Describe the capstone project you would like to pursue, considering your aspirations, ML model predictions, and prior knowledge. Even if you are unsure at this stage, try to generate an idea you would like to explore-such as a specific asset class, country, industry vertical, or investment strategy. Be as specific as possible.

*Example: I want to build a short-term prediction model for the US/India/Brazil stock markets, focusing on the largest stocks over a 30-day investment horizon. I plan to use RSI and MACD technical indicators and news coverage data to generate predictions.*

---
### Question 6. [Exploratory, optional] Investigate new metrics

**Free text answer**

Using the data sources we have covered (or any others you find relevant), download and explore a few additional metrics or time series that could be valuable for your project. Briefly explain why you think each metric is useful. This does not need to be a comprehensive list-focus on demonstrating your ability to generate data requests based on your project description, identify and locate the necessary data, and explain how you would retrieve it using Python.

## Submitting the solutions

Form for submitting: https://courses.datatalks.club/sma-zoomcamp-2025/homework/hw01

---
## Leaderboard

Leaderboard link: https://courses.datatalks.club/sma-zoomcamp-2025/leaderboard

---